main:
  name: "adsb2rmq"
  version: "1.0.0"
  base_path: 'cwd'
  ssid: 'adsb'
  log:
    path: "/log/adsb2rmq"
    name: "main"
    verbose: True
    level: "DEBUG"
thread_enable:
  sbs1: True
  mlat: True
  rmq: True
sbs1:
  name: "adsb" #thread name
  type: "sbs1" #type of device
  connection:
    type: "tcp" #Connection Type: TCP, UDP, Serial
    ip: "10.1.2.10" #IP of dump1090
    port: 30003 #SBS1 (CSV) dump1090 port
    startup_delay: 1 #thread initialization delay
    retry_time: 5 #rate in seconds to attempt device reconnection
    watchdog_time: 10 #rate in seconds to attempt device reconnection
    timeout: 0.001 #Connection Timeout Window
mlat:
  name: "adsb" #thread name
  type: "mlat" #type of device
  connection:
    type: "tcp" #Connection Type: TCP, UDP, Serial
    ip: "10.1.2.10" #IP of dump1090
    port: 30106 #MLAT (CSV) dump1090 port
    startup_delay: 1 #thread initialization delay
    retry_time: 10 #rate in seconds to attempt device reconnection
    watchdog_time: 60 #rate in seconds to attempt device reconnection
    timeout: 0.001 #Connection Timeout Window
rmq:
  name: "RMQ_Thread"
  type: "rmq" #indicates the connection thread for the service uses RabbitMQ
  connection: #Passed to the BrokerConnector class for RMQ Connections
    type: 'daemon' #Options: daemon or client
    ip: "0.0.0.0" #Ip Address of RabbitMQ Broker
    port: 5672  #default IP of RabbitMQ
    user: "adsb"
    pass: "adsb"
    vhost: "adsb"
    exchange: "adsb"
    exchange_key: "adsb"
    exch_type: "topic"
    durable: True
    retry_wait: 5
    update_delay: 0.1
    app_id: "adsb2rmq"
